import type { Metadata } from "next";
import "./globals.css";
import { store } from "@/lib/store";
import { ReduxProvider } from "@/components/shared/reduxprovider";
import Navbar from "@/components/shared/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body>
        <ReduxProvider>
          <Navbar/>
          {children}
        </ReduxProvider>
      </body>

    </html>
  );
}
